name: sancaktar_gcs
description: "Sancaktar Ground Control Station"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_tts: ^4.2.5
  geolocator: ^13.0.2
  speech_to_text: ^7.3.0
  permission_handler: ^11.0.0
  flutter_libserialport: ^0.6.0
  postgres: ^2.6.2
  intl: ^0.19.0

  # Firebase — Linux HARİÇ tüm platformlar
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  firebase_database: ^12.2.0
  cloud_firestore: ^6.2.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true