// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATFbBnOEuLN_cBMPhwj8RqHlvA-BeMo3g',
    appId: '1:829423142948:web:70e02505fc0d4778dff0b1',
    messagingSenderId: '829423142948',
    projectId: 'sancaktar-2025',
    authDomain: 'sancaktar-2025.firebaseapp.com',
    databaseURL: 'https://sancaktar-2025-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sancaktar-2025.firebasestorage.app',
    measurementId: 'G-DHFWR282Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSLjpFWolu-M_COfdHGRvr2A4RA1fDkEo',
    appId: '1:829423142948:android:fef4eca43f867eaddff0b1',
    messagingSenderId: '829423142948',
    projectId: 'sancaktar-2025',
    databaseURL: 'https://sancaktar-2025-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sancaktar-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN2Fape6izALFxqGl8pUgwgO19LykQbLQ',
    appId: '1:829423142948:ios:040a4f94789bd71cdff0b1',
    messagingSenderId: '829423142948',
    projectId: 'sancaktar-2025',
    databaseURL: 'https://sancaktar-2025-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sancaktar-2025.firebasestorage.app',
    iosBundleId: 'com.example.sancaktarGcs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN2Fape6izALFxqGl8pUgwgO19LykQbLQ',
    appId: '1:829423142948:ios:040a4f94789bd71cdff0b1',
    messagingSenderId: '829423142948',
    projectId: 'sancaktar-2025',
    databaseURL: 'https://sancaktar-2025-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sancaktar-2025.firebasestorage.app',
    iosBundleId: 'com.example.sancaktarGcs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATFbBnOEuLN_cBMPhwj8RqHlvA-BeMo3g',
    appId: '1:829423142948:web:1b5c6c5bd70f334adff0b1',
    messagingSenderId: '829423142948',
    projectId: 'sancaktar-2025',
    authDomain: 'sancaktar-2025.firebaseapp.com',
    databaseURL: 'https://sancaktar-2025-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sancaktar-2025.firebasestorage.app',
    measurementId: 'G-Q5TGHP95JM',
  );
}
